//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string product_code { get; set; }
        public string product_name { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> prices { get; set; }
        public byte[] image_url { get; set; }
        public Nullable<bool> delete_status { get; set; }
        public Nullable<int> id_product_category { get; set; }
    
        public virtual product_category product_category { get; set; }
    }
}
